Rank for decomposed classes
cqfn/aibolit pull request #616
Opened 2020-08-14 14:02 UTC by lyriccoder

Please specify the following in the description:

1. fix #613 
2. A description/notes about this pull request.

2020-08-14 14:34 UTC, lyriccoder commented
1) What I see is that current LCOM4 is broken. Untill #615 is not fixed, this PR won't be merged

2) We need to discuss some certain options (Ignore setters, getters, constructors) for LCOM4

3) What should we do with Inner classes?

4) @yegor256 asked to count all unique patterns. We showed number of patterns with total number of patterns:

```
D:\target\0001\fast\Configuration.java  [225]: Non final class (P24: 9.40 1/3)
D:\target\0001\fast\Configuration.java  [225]: Implements Multi (P7: 2.70 2/3)
D:\target\0001\fast\Configuration.java  [3019]: Instance of (P8: 10.80 3/3)
```
Should we now group it by LCOM value, not by a file:
```
D:\target\0001\fast\Configuration.java 1 component  [225]: Non final class (P24: 9.40 1/2)
D:\target\0001\fast\Configuration.java 1 component   [225]: Implements Multi (P7: 2.70 2/2)
D:\target\0001\fast\Configuration.java 2nd component   [3019]: Instance of (P8: 10.80 1/1)
```

If not, in this case it is not useless to extract LCOM component, because ncss value is low for LCOM component and the patterns importance will be increased

2020-08-28 09:17 UTC, aravij requested changes

2020-08-28 09:23 UTC, lyriccoder commented on requirements.txt
> -pebble==4.5.3
fixed, there was a bad merge, i think

2020-08-28 13:10 UTC, aravij approved these changes

2020-08-28 13:12 UTC, acheshkov commented
@rultor merge

2020-08-28 13:18 UTC, acheshkov commented
@rultor merge

2020-08-28 13:19 UTC, rultor commented
> @rultor merge

@acheshkov OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/23143-682552042)

2020-08-28 13:21 UTC, lyriccoder commented
![tenor](https://user-images.githubusercontent.com/20803206/91565199-81a2c000-e94a-11ea-9e57-567ed6e03479.gif)
@rultor?

2020-08-28 14:05 UTC, merged

2020-08-28 14:06 UTC, rultor commented
> @rultor merge

@acheshkov Done! FYI, the full log is [here](https://www.rultor.com/t/23143-682552042) (took me 46min)

2020-08-28 14:09 UTC, rultor commented
> @rultor merge

@acheshkov @lyriccoder The pull request is closed already, so I can't merge it

2020-08-28 14:09 UTC, rultor commented
> @rultor merge

@acheshkov I'm sorry, I don't understand you :( Check [this page](http://doc.rultor.com/basics.html) and try again please